// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
export {};

/**
 * Calculate the Fibonacci sequence up until a limit
 */
const calculateFibonacci = (limit: number) => {
    const sequence = [1, 2];

    // Keep making new numbers in the sequence until we hit the upper bound
    while (sequence[sequence.length - 1] < limit) {
        const newValue = sequence[sequence.length - 1] + sequence[sequence.length - 2];
        sequence.push(newValue);
    }

    return sequence;
};

// Output
const fibonacci = calculateFibonacci(4000000);
const even = fibonacci.filter(n => n % 2 === 0);
const evenSum = even.reduce((a, b) => a + b);

console.log(evenSum);
